IF EXISTS (
SELECT *
	FROM INFORMATION_SCHEMA.ROUTINES
WHERE SPECIFIC_SCHEMA = N'dbo'
	AND SPECIFIC_NAME = N'DA_GetCatById'
	AND ROUTINE_TYPE = N'PROCEDURE'
)
DROP PROCEDURE dbo.DA_GetCatById
GO

CREATE PROCEDURE dbo.DA_GetCatById
	@ID int=0
AS
BEGIN
	SELECT * From Cats WHERE id = @ID;
END
GO